package com.pwz.dao;

import java.util.List;

import com.pwz.model.ElecReading;

public interface ElecReadingDAO {
	/**
	 * @param reading an instance of ElecReading class
	 * @return	      the primary key generated by database
	 */
	int addReading(ElecReading reading);
	ElecReading getReading(int readingId);
	List<ElecReading> getReadings(int acctId);
	void deleteReading(int readingId);
}
