package com.pwz.dao;

import java.util.List;

import com.pwz.model.ElecBill;

public interface ElecBillDAO {
	/**
	 * @param bill an instance of ElecBill class
	 * @return	   the primary key generated by database
	 */
	int addBill(ElecBill bill);
	ElecBill getBill(int billId);
	List<ElecBill> getBills(int acctId);
	void delete(int billId);
}
