package com.pwz.dao;

import java.util.List;

import com.pwz.model.GasAccount;

public interface GasAcctDAO {
	/**
	 * @param account an instance of GasAccount classs
	 * @return		  the primary key generated by database
	 */
	int addAccount(GasAccount account);
	GasAccount getAccount(int gasAcctId);
	void updateAccount(GasAccount account);
	List<GasAccount> listAccounts(int userId);
	void deleteAccount(int acctId);	
}
