package com.pwz.dao;

import java.util.List;

import com.pwz.model.User;

public interface UserDAO {
	/**
	 * @param 	user an instance of User class
	 * @return 		 the primary key generated by database
	 */
	int register(User user);
	User getUser(int userId);
	User getUser(String username);
	List<User> listUsers();
	void delete(int userId);
	void update(User user);
}
